version: 0.0
os: windows
files:
  - source: .
    destination: c:\app
hooks:
  BeforeInstall:
    - location: c:\app\Deployment\beforeinstall.ps1
  ApplicationStart:
    - location: c:\app\Deployment\start.ps1
      timeout: 180
  ValidateService:
    - location: c:\app\Deployment\validate.ps1
      timeout: 180
