version: 0.0
os: windows
files:
  - source: \
    destination: c:\app
hooks:
  ApplicationStart:
    - location: Deployment\start.ps1
      timeout: 180
  ValidateService:
    - location: Deployment\validate.ps1
      timeout: 180
